services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ${REGISTRY}/${WEB_IMAGE}:${TAG}
    ports:
      - "8200:8200"
    depends_on:
      - db
 
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: ${REGISTRY}/${DB_IMAGE}:${TAG}
    volumes:
      - mysql_data:/var/lib/mysql
 
volumes:

  mysql_data:
